on: [push]
name: Test
jobs:
  security:
    name: Review security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: gosec
        uses: "cedrickring/golang-action@1.3.0"
        with:
          args: go get github.com/securego/gosec/cmd/gosec; gosec ./... # https://github.com/securego/gosec
  golangci-lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run GolangCI-Lint Action by building from repository
        uses: matoous/golangci-lint-action@v1.1.0
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
